### ISSUE TITLE
Undefined symbols _GetMacOSStatusCommentString

### ISSUE THREAD

**Issue by ryandesign** [espeak-ng/pcaudiolib#14]
pcaudiolib 1.2 does not build on macOS 11 ("Big Sur") or macOS 12 ("Monterey").

```
Undefined symbols for architecture arm64:
  "_GetMacOSStatusCommentString", referenced from:
      _coreaudio_object_strerror in libpcaudio_la-coreaudio.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [src/libpcaudio.la] Error 1
```

This follows an earlier warning about the same symbol:

```
src/coreaudio.c:259:9: warning: 'GetMacOSStatusCommentString' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
        return GetMacOSStatusCommentString(error);
               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Debugging.h:854:1: note: 'GetMacOSStatusCommentString' has been explicitly marked deprecated here
GetMacOSStatusCommentString(OSStatus err)                     __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_4, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
^
1 warning generated.
```

A full log on macOS 12 arm64 is here:

https://build.macports.org/builders/ports-12_arm64-builder/builds/24340/steps/install-port/logs/stdio

A full log on macOS 11 x86_64 is here:

https://build.macports.org/builders/ports-11_x86_64-builder/builds/53647/steps/install-port/logs/stdio

Some discussion of a possible replacement for this function is here:

https://stackoverflow.com/questions/14699604/replacements-for-getmacosstatuserrorstring-getmacosstatuscommentstring

**Comment by TheQuinbox** [comment]
@alex19EP, this seems fixed in #20
