### ISSUE TITLE
Adding support of Sun audio (NetBSD, Solaris, &)

### ISSUE THREAD

**Issue by adr-adr** [espeak-ng/pcaudiolib#26]
Hi, I'm making a pkgsrc port of pcaudiolib. Could you take a look at these patches? They add support
to the Sun audio interface. The native NetBSD audio interface is compatible with it (with some extensions).

Thanks

[pcaudiolib_add_sun_audio_patches.tgz](https://github.com/espeak-ng/pcaudiolib/files/14057903/pcaudiolib_add_sun_audio_patches.tgz)

**Comment by alex19EP** [comment]
can you make a pr?

**Comment by adr-adr** [comment]
Done.
