### ISSUE TITLE
can new release be tagged?

### ISSUE THREAD

**Issue by alex19EP** [espeak-ng/pcaudiolib#7]
I am especially interested in a41d46e816d2cbcd93564c42b65a87af547bcb2d

thank you.

**Comment by valdisvi** [comment]
By looking how @rhdunn  released 1.1, I created release [1.2](https://github.com/espeak-ng/pcaudiolib/releases/tag/1.2). Hopefully it is correct.

**Comment by alex19EP** [comment]
thank you @valdisvi
