### ISSUE TITLE
Release 1.2 is not mentioned in CHANGELOG.md

### ISSUE THREAD

**Issue by ryandesign** [espeak-ng/pcaudiolib#8]

**Comment by valdisvi** [comment]
I updated file, squashed update commits into single one (rewrote history) and packaged new release [1.2](https://github.com/espeak-ng/pcaudiolib/releases/tag/1.2).

**Comment by ryandesign** [comment]
> rewrote history

AAAAAAAAAA! That's terrible. You should never do that in a public project. Now MacPorts, which I had already updated to version 1.2 before filing this issue, will experience checksum errors when anyone tries to install it because the distribution file it is expecting is not the same as what you now provide. I'll update MacPorts again to fix this, but please don't do it again.
